export const assets: Record<string, string> = {
  "/favicon.svg": "public/favicon.svg",
  "/icon-32.png": "public/icon-32.png",
  "/icon-180.png": "public/icon-180.png",
  "/icon-192.png": "public/icon-192.png",
  "/icon-512.png": "public/icon-512.png",
  "/site.webmanifest": "public/site.webmanifest",
  "/": "public/index.html",
  "/account": "public/account.html",
  "/account.html": "public/account.html",
  "/account.js": "public/account.js",
  "/auth-client.js": "public/auth-client.js",
  "/celebration.js": "public/celebration.js",
  "/calendar-sources.js": "public/calendar-sources.js",
  "/calendar-connect.js": "public/calendar-connect.js",
  "/character.js": "public/character.js",
  "/art/desk-folder-v1.png": "public/art/desk-folder-v1.png",
  "/icons.js": "public/icons.js",
  "/organize.js": "public/organize.js",
  "/links.js": "public/links.js",
  "/planner.js": "public/planner.js",
  "/documents.js": "public/documents.js",
  "/document-worker.js": "public/document-worker.js",
  "/vendor/fflate.js": "node_modules/fflate/esm/browser.js",
  "/sync.js": "public/sync.js",
  "/ui-state.js": "public/ui-state.js",
  "/drafts.js": "public/drafts.js",
  "/app.js": "public/app.js",
  "/logic.js": "public/logic.js",
  "/pdf.js": "public/pdf.js",
  "/pdf/pdf.min.mjs": "node_modules/pdfjs-dist/build/pdf.min.mjs",
  "/pdf/pdf.worker.min.mjs": "node_modules/pdfjs-dist/build/pdf.worker.min.mjs",
  "/style.css": "public/style.css",
  "/ocr/tesseract.min.js": "node_modules/tesseract.js/dist/tesseract.min.js",
  "/ocr/worker.min.js": "node_modules/tesseract.js/dist/worker.min.js",
  "/ocr/eng.traineddata.gz":
    "node_modules/@tesseract.js-data/eng/4.0.0/eng.traineddata.gz",
};
